version: '3'

services:
  postgres:
    container_name: 'app-name-postgres'
    restart: unless-stopped
    image: 'postgres:13@sha256:4a63d91c51ca0ef6f15b0c54690a945f15afb50d86ef147484a5dbd466c670b3'
    ports:
      - '15432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: postgres
  nextjs:
    build: ./
    ports:
      - 3000:3000

volumes:
  pgdata: {}
