version: '3'

services:
  postgres:
    container_name: 'app-name-postgres'
    restart: unless-stopped
    image: 'postgres:14@sha256:b0ee049a2e347f5ec8c64ad225c7edbc88510a9e34450f23c4079a489ce16268'
    ports:
      - '15432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: postgres
  nextjs:
    build: ./
    ports:
      - 3000:3000

volumes:
  pgdata: {}
