version: '3'

services:
  postgres:
    container_name: 'app-name-postgres'
    restart: unless-stopped
    image: 'postgres:14@sha256:2d0a19f476f067e4540698c1deb4455450398d3f2aef13dd62600c131931cf09'
    ports:
      - '15432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: postgres
  nextjs:
    build: ./
    ports:
      - 3000:3000

volumes:
  pgdata: {}
