name: Run automated tests - PR
on:
  pull_request:
    branches:
      - main
      - canary

jobs:
  build:
    name: Build the Code
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        if: ${{ steps.docs-change.outputs.docsChange != 'docs only change' }}
        with:
          node-version: 14

      - uses: actions/checkout@v2
        with:
          fetch-depth: 25

      - name: Install Deps
        run: yarn install --frozen-lockfile --check-files
      - name: Run Build
        run: yarn build

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  formatting:
    name: Formatting Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - run: yarn format:check

  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - run: yarn typecheck

  lint:
    name: Linting Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
      - run: yarn lint

  testUnit:
    name: Test Units
    runs-on: ubuntu-latest
    needs: [build, lint]
    env:
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_TEST_JOB: 1
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        if: ${{ steps.docs-change.outputs.docsChange != 'docs only change' }}
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

      - run: yarn test
